[AF-2649] Add params
jesuino/dashbuilder-components pull request #27
Opened 2020-11-09 14:41 UTC by manaswinidas

Fixes #24

2020-11-30 18:39 UTC, jesuino requested changes
Hello @manaswinidas 

Thank you so much for the great improvements! 

The CSS properties are working very well. The dataset is now columns based, meaning that each column is the BAR, which makes easier to use existing datasets, thanks again!

I noticed a few issues:

1) I see that disabling title property is not working anymore - I click to disable but the title continues showing;
2) I see a lost "undefined" at the end of the bar chart
3) Finally the bars are still not changing position, this may be due some specific issue with the API in my setup, we can discuss later what could be different in my environment.

Besides that, the components looks great, thanks for your work on it! I am waiting for these changes so we can merge this comp.

Thanks!


![dynamic_bar](https://user-images.githubusercontent.com/359820/100649771-b21b4100-3321-11eb-8cd7-1d6d3793370f.gif)

2020-11-30 18:39 UTC, jesuino commented on bar-chart-race/src/ChartRace.tsx
> +        titleenabled: titleenabled || TITLE_ENABLED,
This will always resolve to true - AND operation instead OR should work

2020-11-30 19:51 UTC, manaswinidas commented
Hi @jesuino thanks for reviewing! Sorry for missing the "undefined" earlier :sweat_smile: I have fixed the disable title too. Not sure why the bars aren't changing position on your end, seems to work fine on my end. Will have to have a closer look at it. Might be a potential bug.

2021-01-11 16:55 UTC, jesuino commented
Thanks, @manaswinidas  - I am merging this PR to start our API migration

2021-01-11 16:56 UTC, jesuino approved these changes

2021-01-11 16:56 UTC, merged