Migrate treemap-recharts to new API
jesuino/dashbuilder-components pull request #41
Opened 2021-01-29 15:49 UTC by manaswinidas

2021-02-10 19:39 UTC, jesuino requested changes
Hello @manaswinidas 

The component looks good to me, thanks!

I have a few questions for your in my review, would you please check it?

THanks!

2021-02-10 19:39 UTC, jesuino commented on packages/treemap-recharts/package.json
> +  },
is this needed?

2021-02-10 19:39 UTC, jesuino commented on packages/treemap-recharts/src/Treemaps.tsx
> +  console.log(props.data);
Can we remove this log line?

2021-02-10 19:39 UTC, jesuino commented on packages/treemap-recharts/src/serviceWorker.ts
> +// This optional code is used to register a service worker.
Is this file needed?

2021-02-10 19:39 UTC, jesuino commented on packages/treemap-recharts/src/setupTests.ts
> +// jest-dom adds custom jest matchers for asserting on DOM nodes.
is this file being usedw

2021-02-11 07:44 UTC, manaswinidas commented
Sorry for not cleaning up earlier 😅

2021-02-19 18:15 UTC, jesuino approved these changes
LGTM, thanks!

2021-02-19 18:16 UTC, merged